.TH trojan 1 "Aug 2018" "version 1.6.0"
.SH NAME
trojan \- an unidentifiable mechanism that helps you bypass GFW
.SH SYNOPSIS
.B trojan
.I config_file
.SH DESCRIPTION
.B trojan
is an unidentifiable mechanism that helps you bypass GFW. It will load the
config file located in
.I config_file
and start either a proxy client or a proxy server.
.SH SEE ALSO
Full documentation at: <https://trojan-gfw.github.io/trojan/>
